### ISSUE TITLE
add member.iotex.io/tools/reclaim --> to support reclaim bucket

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/web-native-staking-v2#122]
add a webpage tools --> "Reclaim Bucket" to allow user to reclaim a HDWallet-owned bucket

`step 1: input bucket index and recipient`
"Enter the bucket index you wish to reclaim, and the recipient's address (new owner of this bucket)"
1. a text field to enter the bucket index 
2. a text field to enter the recipient address (for example "io14s0vgnj0pjnazu4hsqlksdk7slah9vcfscn9ks")

`step 2: give the option of ioctl`
"You can reclaim the bucket by running the following ioctl command:
`ioctl stake2 reclaim index Ethereum -s recipient -p 1 -l 300000`"
recipient = address in step 1
index = the bucket that user wants to transfer
"or if you wish to use the web tool, make sure ioPay is opened (and it has the recipient private key/account), then click Continue"

Upon user click the "Continue" button:

`step 2: create the message for user to sign using HDWallet`
3. marshal these inputs into the following JSON struct: (https://github.com/iotexproject/iotex-core/blob/master/action/consignment_transfer.go#L57-L63)
```
struct {
	BucketIdx int    `json:"bucket"`
	Nonce     int    `json:"nonce"`
	Recipient string `json:"recipient"`
	Reclaim   string `json:"reclaim"`
}
```
see https://etherscan.io/verifySig/2080 for an example of such a message 

4. display the entire message, a copy button so user can easily copy this meesage (exact message in [Step 3] of https://etherscan.io/verifySig/2080, with correct value of bucket and nonce)

5. ask the user to sign this message using HDWallet, and come back with signature

`step 3: construct the payload of the transfer action`
6. a text field to ask user to paste the signature bytes from HDWallet ([Step 2] of https://etherscan.io/verifySig/2080)
7. marshal these inputs into the following JSON struct: (https://github.com/iotexproject/iotex-core/blob/master/action/consignment_transfer.go#L66-L70)
```
struct {
	Type string `json:"type"`
	Msg  string `json:"msg"`
	Sig  string `json:"sig"`
}
```
Type = "Ethereum"
Msg = [Step 3] of https://etherscan.io/verifySig/2080
Sig = [Step 2] of https://etherscan.io/verifySig/2080

`step 4: construct and send the bucket transfer action`
1. construct a stakeTransfer message, https://github.com/iotexproject/iotex-proto/blob/master/proto/types/action.proto#L80-L84
with payload = bytes in step7
2. sign this message using ioPay (with recipient's private key/account), and send it to blockchain

**Comment by dustinxie** [comment]
please continue working on step3~4

**Comment by hunglmtb** [comment]
I tried to do sign message and send to chain, but got `ErrUnauthorizedOperator`, that means the signer not match the owner bucket. 
here my data (on testnet https://api.testnet.iotex.one )
```
{
	"type": "Ethereum",
	"msg": {
		"bucket": 53,
		"nonce": 35,
		"recipient": "io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80",
		"reclaim": "This is to certify I am transferring the ownership of said bucket to said recipient on IoTeX blockchain"
	},
	"sig": "0x88d57c04cfb78feabd2e8d3ee6e152fd39ddfd88175524500abca13c15980fe734f362140012467fc56e5e8e2de12e27aebb15bc1abfb8a9164292531b1ffd5c1b"
}
```
https://testnet.iotexscan.io/action/cb1f8ca88a7b16ceb6d05bfbf24cc696c449677040187bab2605baac1da4092a

I checked the bucket id 53, it belongs `io1crkagrkzypfmsjwthyccrhgk29rj6epsee4dsy `/ `0xc0edd40ec22053b849cbb93181dd1651472d6430` 
I could not run` ioctl bc bucket` at my side - windows -my latest ioctl release (2019-11-27)  not support bucket cli command. my ubtuntu is broken now

**Comment by dustinxie** [comment]
thx Hung for the very detailed data points!

so i checked the tx on testnet `ioctl action hash cb1f8ca88a7b16ceb6d05bfbf24cc696c449677040187bab2605baac1da4092a --endpoint=api.testnet.iotex.one:443`, it gives:

```
stakeTransferOwnership: <
  bucketIndex: 53
  voterAddress: "io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80"
  payload: "{\"type\":\"Ethereum\",\"msg\":{\"bucket\":53,\"nonce\":34,\"recipient\":\"io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80\",\"reclaim\":\"This is to certify I am transferring the ownership of said bucket to said recipient on IoTeX blockchain\"},\"sig\":\"0x907e7d3e0ac60f7d7f0e387c912bba37b2751319c29a39a1962f0a19f2b3bd6e4ee9c1ac23eab0c264c48d4def2a942d92a2da4d61c6a6109719d09bd653b1eb1c\"}"
>
```

1. the `sig` data does not match what you pasted above, it is `907e7d3e` instead of `88d57c04 ...`
2. there is still `0x` at beginning of sig, need to remove that

**Comment by dustinxie** [comment]
@hunglmtb  i also verified, the `sig` bytes you sent in the action `907e7d3e0ac60f7d7f0e387c912bba37b2751319c29a39a1962f0a19f2b3bd6e4ee9c1ac23eab0c264c48d4def2a942d92a2da4d61c6a6109719d09bd653b1eb1c` is a valid signature from original owner `io1crkagrkzypfmsjwthyccrhgk29rj6epsee4dsy ` 
so all you have to do is remove `0x` at beginning

**Comment by hunglmtb** [comment]
I tried to remove `0x` of `sig` but it still got unauthorized status
my sent data
```
{
	"type": "Ethereum",
	"msg": {
		"bucket": 53,
		"nonce": 42,
		"recipient": "io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80",
		"reclaim": "This is to certify I am transferring the ownership of said bucket to said recipient on IoTeX blockchain"
	},
	"sig": "75fd1c202aad4ea0c19995d1cefc3038797a8c90fc53749786e682f419f305d2598fa4d8a815620c87be4b55e1f054a1a5cb1e756a1879ce17a5a8d12759c9d11b"
}
```

and hash https://testnet.iotexscan.io/action/e172c27b0f973845df8c045d38f76ec9f506876003c702c0aea41d6ee7f32aed
Could you help to check ? @dustinxie

**Comment by dustinxie** [comment]
here's the payload from action data on testnet

```
"{\"type\":\"Ethereum\",\"msg\":{\"bucket\":53,\"nonce\":42,\"recipient\":\"io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80\",\"reclaim\":\"This is to certify I am transferring the ownership of said bucket to said recipient on IoTeX blockchain\"},\"sig\":\"75fd1c202aad4ea0c19995d1cefc3038797a8c90fc53749786e682f419f305d2598fa4d8a815620c87be4b55e1f054a1a5cb1e756a1879ce17a5a8d12759c9d11b\"}"
```

i verified recipient, bucket, nonce, and signature are all correct, and here's the `payload` reconstructed:
```
{"type":"Ethereum","msg":"{\"bucket\":53,\"nonce\":42,\"recipient\":\"io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80\",\"reclaim\":\"This is to certify I am transferring the ownership of said bucket to said recipient on IoTeX blockchain\"}","sig":"75fd1c202aad4ea0c19995d1cefc3038797a8c90fc53749786e682f419f305d2598fa4d8a815620c87be4b55e1f054a1a5cb1e756a1879ce17a5a8d12759c9d11b"}
```

**Comment by hunglmtb** [comment]
here my some modified ways to sent payload without `\"`, I also debugged sindAndSend via iopay desktop and android, and deserialize to check payload before send to chain, it does not contain `\"` but the action hash info always has `\"` when checking  `ioctl action hash` .
In the case of payload is single `"`, the deserialized one has `\"`
```
ioctl action hash 306b5be636f2f53a2b5b066a97bda05c5bba95a2801824c958676dd413a1fcb8 --endpoint=api.testnet.iotex.one:443

stakeTransferOwnership: <
  bucketIndex: 53
  voterAddress: "io1k7rqg4ksjx93f467mdfjzm6un6ezskwcppls80"
  payload: "\""
>
```
 some of way to serialize payload at client-side I tried to
```
// user JSON stringify
Buffer.from(JSON.stringify(payload))`

TextEncoder
```

```
//use directly string
const payload = `{"type":"Ethereum","msg":"${JSON.stringify(this.state.jsonMessage)}","sig":"${this.state.sig.replace("0x", "")}"}`;
Buffer.from(payload )`
```

```
//customize serialize function
export function serializeBuffer(payload: object): Uint8Array {
  const start = Buffer.from("{");
  const list = [start];
  const keys = Object.keys(payload);
  keys.forEach((key, index)=>{
    const bKey = Buffer.from(String.fromCharCode(0x22)+key+String.fromCharCode(0x22)+String.fromCharCode(0x3a));
    list.push(bKey);
    const value = payload[key];
    if(typeof value === "number"){
      list.push(Buffer.from(`${value}`));
    } else if(typeof value === "string"){
      list.push(Buffer.from(String.fromCharCode(0x22)+value+String.fromCharCode(0x22)));
    }
    if(index<keys.length-1){
      list.push(Buffer.from(","));
    }
  });
  list.push(Buffer.from("}"))
  return Buffer.concat(list);
}


```
and more detail sent data to retrieve the action
```
const payload = {
      type: "Ethereum",
      msg: JSON.stringify(this.state.jsonMessage),
      sig: sig.replace("0x", "")
    };

  StakeTransferOwnership = {
    bucketIndex: bucketIndex,
    voterAddress: address,
    payload: payload,
  }
```

I push my code to https://github.com/iotexproject/web-native-staking-v2/pull/267
Could you help to check what wrong ? @dustinxie @ququzone

**Comment by dustinxie** [comment]
here's a success example on testnet:
`ioctl action hash 22cd0c2d1f7d65298cec7599e2d0e3c650dd8b4ed2b1c816d909026c60d785b2 --endpoint=api.testnet.iotex.one:443`
actual payload from that tx:
```
"{\"type\":\"Ethereum\",\"msg\":\"{\\\"bucket\\\":57,\\\"nonce\\\":1,\\\"recipient\\\":\\\"io1ed52svvdun2qv8sf2m0xnynuxfaulv6jlww7ur\\\",\\\"reclaim\\\":\\\"This is to certify I am transferring the ownership of said bucket to said recipient on IoTeX blockchain\\\"}\",\"sig\":\"5c6ee16cf2db4a017c09bdc4115668b1fff0a9ec2981ce1326eb901df4997094051dd8cc96e760cb160449db0ca641dc0057a09b410e44603df015a64394b6d61c\"}"
```

**Comment by dustinxie** [comment]
here's Go code to generate payload

```go
payload, err := action.NewConsignJSON(args[1], sender, sig, bucketIndex, nonce)
```
and
```go
// NewConsignJSON creates a consignment JSON from inputs
func NewConsignJSON(sigType, recipient, sig string, bucketIdx, nonce uint64) ([]byte, error) {
	msgBytes, err := NewConsignMsg(sigType, recipient, bucketIdx, nonce)
	if err != nil {
		return nil, err
	}

	msgJSON := ConsignJSON{
		Type: sigType,
		Msg:  string(msgBytes),
		Sig:  sig,
	}
	msgBytes, err = json.Marshal(msgJSON)
	if err != nil {
		return nil, err
	}
	return msgBytes, nil
}
```
