### ISSUE TITLE
some link is not https (images)

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#162]
![image](https://user-images.githubusercontent.com/448293/85624901-787e3580-b61f-11ea-8466-6cd426a8103d.png)

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/89242183-c6d70a80-d5b5-11ea-8804-ffa0dd534f22.png)

**Comment by liaojikunwork** [comment]
I tried to reproduce that issue but couldn't see it on my side

**Comment by guo** [comment]
still repo.

**Comment by guo** [comment]
![image](https://user-images.githubusercontent.com/448293/90288627-1bd51500-de2f-11ea-9fb8-0f91c8c39cc0.png)
![image](https://user-images.githubusercontent.com/448293/90288639-2099c900-de2f-11ea-9d19-d6ef5afd07ee.png)
![image](https://user-images.githubusercontent.com/448293/90288649-28596d80-de2f-11ea-9846-a60e1c9b92a2.png)

**Comment by guo** [comment]
if you query
```
 query stats {
    bpCandidates {
      name
      productivity
      productivityBase
      category
      badges
      logo
    }
  }
```

**Comment by guo** [comment]
it is best just change the server return value. do a replacement there.

**Comment by guo** [comment]
no need to change database.
