### ISSUE TITLE
Android browser compatiiblity issue

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#213]
![image](https://user-images.githubusercontent.com/448293/87404249-c5945e00-c572-11ea-97de-0eccb19b8ba8.png)

voting website does not work withchrome 62 or lower webkit on Android due to csp conflict with jsbridge.

**Comment by guo** [comment]
We can fix by removing csp for chrome 62 or lower webkit on Android.

**Comment by hunglmtb** [comment]
`yy://jb-queue-message/` an `https://bridge-loaded` are used in iopay app to register jbridge. iopay app on android devices with newer chrome version works without the above error.  chrome 62 or lower webkit on Android seems to ignore these schema. 
Removing csp will work onthese Android devices https://github.com/iotexproject/web-native-staking-v2/blob/4f91f6a88828729bbc8bbefdf18f2a0626b2170b/config/default.js#L46-L93
Now we need to remove this csp by detect android iopay with chrome version. To check request  source from iopay android, you can refer here
https://github.com/iotexproject/web-native-staking-v2/blob/4f91f6a88828729bbc8bbefdf18f2a0626b2170b/src/server/server-routes.tsx#L90-L103
