### ISSUE TITLE
Replace the IoTeX logo with the delegate's logo

### ISSUE THREAD

**Issue by loriIoTeX** [iotexproject/web-native-staking-v2#216]
![image](https://user-images.githubusercontent.com/38968374/87511240-d6ec7180-c629-11ea-93b9-33e2f2b1b8d8.png)

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-07-20 at 11 20 08 PM](https://user-images.githubusercontent.com/34900782/88009055-98e6c600-cadf-11ea-8f9d-6bc14c2a1559.png)
![Screen Shot 2020-07-20 at 11 21 15 PM](https://user-images.githubusercontent.com/34900782/88009081-a9973c00-cadf-11ea-8f79-939bbcf411de.png)

![Screen Shot 2020-07-20 at 11 21 53 PM](https://user-images.githubusercontent.com/34900782/88009133-c3d11a00-cadf-11ea-93b4-3186da3f0da4.png)
I should get Candidate Information with canName.
But I can't query with canName
Could you help ms pls?

**Comment by hunglmtb** [comment]
You can get all delegates by `bpCandidates` query, then lookup by candidate name in the retrieved array @liaojikunwork

**Comment by liaojikunwork** [comment]
ok
