### ISSUE TITLE
use cdn-m2.iotex.io as CDN base

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#227]
we have added cdn-m2.iotex.io as CNAME of web-native-staking-v2.b-cdn.net.
we can migrate to cdn-m2.iotex.io for CDN usage to keep domain access with iotex.io

![image](https://user-images.githubusercontent.com/448293/87981896-d2411680-ca8a-11ea-9094-e494324fea64.png)

**Comment by liaojikunwork** [comment]
So what should I do exactly?  Change all "web-native-staking-v2.b-cdn.net" to "cdn-m2.iotex.io" ?

![Screen Shot 2020-07-21 at 11 57 53 AM](https://user-images.githubusercontent.com/34900782/88077515-5b1e8780-cb49-11ea-880f-ad0666fe86b0.png)

**Comment by guo** [comment]
no need to change at this moment.
