### ISSUE TITLE
update the number based on query results

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#236]
![image](https://user-images.githubusercontent.com/448293/88473022-2c4c3c80-cece-11ea-9288-beeb2e55c560.png)

**Comment by liaojikunwork** [comment]
@guo , which page can I see that and what query should I use?

**Comment by raullenchai** [comment]
> @guo , which page can I see that and what query should I use?

Front page of https://member.iotex.io/, top left corner

**Comment by raullenchai** [comment]
https://docs.iotex.io/docs/analytics.html#delegate may have the useful query

**Comment by liaojikunwork** [comment]
Alright

**Comment by liaojikunwork** [comment]
@raullenchai  , That number is the count of delegates under delegate list, right?

**Comment by raullenchai** [comment]
> @raullenchai , That number is the count of delegates under delegate list, right?
> 
> ![Screen Shot 2020-08-01 at 8 23 46 AM](https://user-images.githubusercontent.com/34900782/89101702-502ce800-d3d0-11ea-8724-d53ef596854a.png)

right

**Comment by liaojikunwork** [comment]
@raullenchai , should I hide that sentence until I get the count of delegates?
Or show 55 at first and update after getting the count of delegates?

**Comment by raullenchai** [comment]
> @raullenchai , should I hide that sentence until I get the count of delegates?
> Or show 50+ at first and update after getting the count of delegates?

the former

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-01 at 9 11 45 AM](https://user-images.githubusercontent.com/34900782/89102423-03004480-d3d7-11ea-95ab-5e8185d4e1c8.png)

?
