### ISSUE TITLE
Hermes badge is missing

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#240]
![image](https://user-images.githubusercontent.com/448293/89134106-1d214c00-d4d7-11ea-8830-f729189887d9.png)

**Comment by hunglmtb** [comment]
from https://member.iotex.io/api-gateway/
```
query bpCandidates {
  bpCandidates {
    name
    status
    badges
  }
}
```
header `{"x-iotex-client-id":"iotex-explorer"}`

query hermes from analytic https://analytics.iotexscan.io/query/
```

query hermes($startEpoch: Int!,
  $epochCount: Int!, 
  $rewardAddress: String!,
  $waiverThreshold: Int!) {  
    hermes(startEpoch: $startEpoch, 
      epochCount: $epochCount, 
      rewardAddress: $rewardAddress,
      waiverThreshold: $waiverThreshold) { 
      hermesDistribution {    
        delegateName 
      }
    }
  }
```

variables: startEpoch change by time
```

{
  "startEpoch": 11200, 
      "epochCount": 1,
      "rewardAddress":  "io12mgttmfa2ffn9uqvn0yn37f4nz43d248l2ga85",
      "waiverThreshold":  100
}
```
header `{"x-iotex-client-id":"iotex-explorer"}`

**Comment by hunglmtb** [comment]
checked with staging https://web-bp-staging.herokuapp.com/
need to set ranking service endpoint `RANKING_SERVICE_URL=https://analytics.iotexscan.io/query` response hermes
the current one `35.185.52.92:8089 `return none of hermes
