### ISSUE TITLE
nulld shown in votes list

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#253]
https://member.iotex.io/delegate/5c736c3738166122d79c9aef/votes
![411596948687_ pic_hd](https://user-images.githubusercontent.com/448293/89725966-5de2fe80-d9ca-11ea-9707-36b2139d8311.jpg)
![401596948576_ pic_hd](https://user-images.githubusercontent.com/448293/89725968-5f142b80-d9ca-11ea-9f6c-a6047d79a716.jpg)
![391596948564_ pic_hd](https://user-images.githubusercontent.com/448293/89725969-60455880-d9ca-11ea-9888-adae5f78b3e4.jpg)

**Comment by hunglmtb** [comment]
we have to move this query from web-bp to analytics directly. webbp is unstable now, it returns empty now

**Comment by guo** [comment]
OK. we can move.
