### ISSUE TITLE
replace https://res.cloudinary.com/ with https://imgc.iotex.io/ in all images urls

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#260]

**Comment by guo** [comment]
for example, the bucket image (delegate profile) in myvotes is cloudinary.

**Comment by guo** [comment]
We have imgc.iotex.io as the cdn to res.cloudinary.com

**Comment by guo** [comment]
refer to 
https://github.com/iotexproject/web-native-staking-v2/blob/fe725cd781e04bae7b81845073c6a7ea6655f9b4/src/shared/common/image.tsx#L55

and update some return values as well. such as bucket image, banner. etc. for those stored on cloudinary.

**Comment by liaojikunwork** [comment]
@guo, could you share more details? 
Do you want to change all asset urls using that?

**Comment by guo** [comment]
no more at this moment.
