### ISSUE TITLE
rank is missing in delegate profile

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#271]
![image](https://user-images.githubusercontent.com/448293/90295157-0ebf2280-de3d-11ea-99d9-76d81f890b10.png)

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-15 at 8 17 04 AM](https://user-images.githubusercontent.com/34900782/90312103-c43ab600-decf-11ea-99ab-c7270d39eb81.png)

![Screen Shot 2020-08-15 at 8 19 11 AM](https://user-images.githubusercontent.com/34900782/90312138-04019d80-ded0-11ea-98ca-1545f00c99c1.png)


There's an issue with bpCandidate graphql api

**Comment by liaojikunwork** [comment]
@hunglmtb , please ping me once you fix getBpCandidate query
