### ISSUE TITLE
params data is missing

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#272]
![image](https://user-images.githubusercontent.com/448293/90295198-27c7d380-de3d-11ea-8098-96fae52cc6e8.png)

**Comment by liaojikunwork** [comment]
@guo, the response of "getting params" query is empty.
![Screen Shot 2020-08-19 at 9 51 21 AM](https://user-images.githubusercontent.com/34900782/90643691-d8e5b980-e201-11ea-80ae-05b5e074e406.png)
