### ISSUE TITLE
Add Hermes ratio to profile

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#273]
![image](https://user-images.githubusercontent.com/448293/90295375-a6bd0c00-de3d-11ea-98ea-fb6910e6c2a9.png)

**Comment by guo** [comment]
if use hermes:

show the text: Distribution Ratios (via <a >Hermes</a>): xx% A, yy % B, zz% C. <a link to hermes query>More details</a>

The hermes query does not have a permalink url yet. You can create one. (now you have to enter the delegate name to search on hermes.to).

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-15 at 8 53 35 PM](https://user-images.githubusercontent.com/34900782/90324171-693da900-df39-11ea-98c8-7dcea7cf5e42.png)


How should I calculate "xx% A, yy % B, zz% C" ?

**Comment by liaojikunwork** [comment]
Distribution Ratios (via Hermes): 0% block reward, 85% epoch reward, 0% foundation bonus reward.

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-16 at 9 55 38 AM](https://user-images.githubusercontent.com/34900782/90335979-b73cc600-dfa6-11ea-8e22-34a6ba8916eb.png)

@guo  does it look good?

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-16 at 9 59 01 AM](https://user-images.githubusercontent.com/34900782/90336039-274b4c00-dfa7-11ea-92c5-301aa6b6274a.png)
 
or is this better?
