### ISSUE TITLE
add badges to delegate profile

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#274]
![image](https://user-images.githubusercontent.com/448293/90295861-e3d5ce00-de3e-11ea-9da0-89d37330f107.png)

**Comment by liaojikunwork** [comment]
![Screen Shot 2020-08-15 at 8 36 19 PM](https://user-images.githubusercontent.com/34900782/90323984-08ad6c80-df37-11ea-8591-5093cabef8b4.png)

There's an issue with bpCandidate query.

**Comment by liaojikunwork** [comment]
@hunglmtb , please ping me once you fix getBpCandidate query
