### ISSUE TITLE
productivity -> Epoch Progress

### ISSUE THREAD

**Issue by guo** [iotexproject/web-native-staking-v2#286]
![image](https://user-images.githubusercontent.com/448293/92299406-c3ada200-ef06-11ea-8ff3-eaaf181d5bcf.png)

**Comment by blesstosam** [comment]
when this pr  https://github.com/iotexproject/iotex-react-components/pull/212/files is merged, we can use it like this:
```js
const rep = [{key: 'productivity', title: 'some other title'}]
  <BlockProducersA
              apolloClient={apolloClient}
              columnsTitleReplace={rep}
            />
```
